apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chapchu-api
  namespace: chapchu
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: api.chapchu.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chapchu-api
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chapchu-auth
  namespace: chapchu
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: auth.chapchu.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chapchu-auth
                port:
                  number: 9000
